from medius.rtpackets import *

class RtId():
    map = {
            0x00 : {'name': 'CLIENT_CONNECT_TCP', 'serializer': clientconnecttcp.ClientConnectTcpSerializer(), 'handler': clientconnecttcp.ClientConnectTcpHandler()},
            0x01 : {'name': 'CLIENT_DISCONNECT', 'serializer': clientdisconnect.ClientDisconnectSerializer(), 'handler': clientdisconnect.ClientDisconnectHandler()},
            0x02 : {'name': 'CLIENT_APP_BROADCAST', 'serializer': clientappbroadcast.ClientAppBroadcastSerializer(), 'handler': clientappbroadcast.ClientAppBroadcastHandler()},
            0x03 : {'name': 'CLIENT_APP_SINGLE', 'serializer': clientappsingle.ClientAppSingleSerializer(), 'handler': clientappsingle.ClientAppSingleHandler()},
            0x04 : {'name': 'CLIENT_APP_LIST', 'serializer': clientapplist.ClientAppListSerializer(), 'handler': clientapplist.ClientAppListHandler()},
            0x05 : {'name': 'CLIENT_ECHO', 'serializer': clientecho.ClientEchoSerializer(), 'handler': clientecho.ClientEchoHandler()},
            0x06 : {'name': 'SERVER_CONNECT_REJECT', 'serializer': serverconnectreject.ServerConnectRejectSerializer(), 'handler': serverconnectreject.ServerConnectRejectHandler()},
            0x07 : {'name': 'SERVER_CONNECT_ACCEPT_TCP', 'serializer': serverconnectaccepttcp.ServerConnectAcceptTcpSerializer(), 'handler': serverconnectaccepttcp.ServerConnectAcceptTcpHandler()},
            0x08 : {'name': 'SERVER_CONNECT_NOTIFY', 'serializer': serverconnectnotify.ServerConnectNotifySerializer(), 'handler': serverconnectnotify.ServerConnectNotifyHandler()},
            0x09 : {'name': 'SERVER_DISCONNECT_NOTIFY', 'serializer': serverdisconnectnotify.ServerDisconnectNotifySerializer(), 'handler': serverdisconnectnotify.ServerDisconnectNotifyHandler()},
            0x0a : {'name': 'SERVER_APP', 'serializer': serverapp.ServerAppSerializer(), 'handler': serverapp.ServerAppHandler()},
            0x0b : {'name': 'CLIENT_APP_TOSERVER', 'serializer': clientapptoserver.ClientAppToserverSerializer(), 'handler': clientapptoserver.ClientAppToserverHandler()},
            0x0c : {'name': 'UDP_APP', 'serializer': udpapp.UdpAppSerializer(), 'handler': udpapp.UdpAppHandler()},
            0x0d : {'name': 'CLIENT_SET_RECV_FLAG', 'serializer': clientsetrecvflag.ClientSetRecvFlagSerializer(), 'handler': clientsetrecvflag.ClientSetRecvFlagHandler()},
            0x0e : {'name': 'CLIENT_SET_AGG_TIME', 'serializer': clientsetaggtime.ClientSetAggTimeSerializer(), 'handler': clientsetaggtime.ClientSetAggTimeHandler()},
            0x0f : {'name': 'CLIENT_FLUSH_ALL', 'serializer': clientflushall.ClientFlushAllSerializer(), 'handler': clientflushall.ClientFlushAllHandler()},
            0x10 : {'name': 'CLIENT_FLUSH_SINGLE', 'serializer': clientflushsingle.ClientFlushSingleSerializer(), 'handler': clientflushsingle.ClientFlushSingleHandler()},
            0x11 : {'name': 'SERVER_FORCED_DISCONNECT', 'serializer': serverforceddisconnect.ServerForcedDisconnectSerializer(), 'handler': serverforceddisconnect.ServerForcedDisconnectHandler()},
            0x12 : {'name': 'CLIENT_CRYPTKEY_PUBLIC', 'serializer': clientcryptkeypublic.ClientCryptkeyPublicSerializer(), 'handler': clientcryptkeypublic.ClientCryptkeyPublicHandler()},
            0x13 : {'name': 'SERVER_CRYPTKEY_PEER', 'serializer': servercryptkeypeer.ServerCryptkeyPeerSerializer(), 'handler': servercryptkeypeer.ServerCryptkeyPeerHandler()},
            0x14 : {'name': 'SERVER_CRYPTKEY_GAME', 'serializer': servercryptkeygame.ServerCryptkeyGameSerializer(), 'handler': servercryptkeygame.ServerCryptkeyGameHandler()},
            0x15 : {'name': 'CLIENT_CONNECT_TCP_AUX_UDP', 'serializer': clientconnecttcpauxudp.ClientConnectTcpAuxUdpSerializer(), 'handler': clientconnecttcpauxudp.ClientConnectTcpAuxUdpHandler()},
            0x16 : {'name': 'CLIENT_CONNECT_AUX_UDP', 'serializer': clientconnectauxudp.ClientConnectAuxUdpSerializer(), 'handler': clientconnectauxudp.ClientConnectAuxUdpHandler()},
            0x17 : {'name': 'CLIENT_CONNECT_READY_AUX_UDP', 'serializer': clientconnectreadyauxudp.ClientConnectReadyAuxUdpSerializer(), 'handler': clientconnectreadyauxudp.ClientConnectReadyAuxUdpHandler()},
            0x18 : {'name': 'SERVER_INFO_AUX_UDP', 'serializer': serverinfoauxudp.ServerInfoAuxUdpSerializer(), 'handler': serverinfoauxudp.ServerInfoAuxUdpHandler()},
            0x19 : {'name': 'SERVER_CONNECT_ACCEPT_AUX_UDP', 'serializer': serverconnectacceptauxudp.ServerConnectAcceptAuxUdpSerializer(), 'handler': serverconnectacceptauxudp.ServerConnectAcceptAuxUdpHandler()},
            0x1a : {'name': 'SERVER_CONNECT_COMPLETE', 'serializer': serverconnectcomplete.ServerConnectCompleteSerializer(), 'handler': serverconnectcomplete.ServerConnectCompleteHandler()},
            0x1b : {'name': 'CLIENT_CRYPTKEY_PEER', 'serializer': clientcryptkeypeer.ClientCryptkeyPeerSerializer(), 'handler': clientcryptkeypeer.ClientCryptkeyPeerHandler()},
            0x1c : {'name': 'SERVER_SYSTEM_MESSAGE', 'serializer': serversystemmessage.ServerSystemMessageSerializer(), 'handler': serversystemmessage.ServerSystemMessageHandler()},
            0x1d : {'name': 'SERVER_CHEAT_QUERY', 'serializer': servercheatquery.ServerCheatQuerySerializer(), 'handler': servercheatquery.ServerCheatQueryHandler()},
            0x1e : {'name': 'SERVER_MEMORY_POKE', 'serializer': servermemorypoke.ServerMemoryPokeSerializer(), 'handler': servermemorypoke.ServerMemoryPokeHandler()},
            0x1f : {'name': 'SERVER_ECHO', 'serializer': serverecho.ServerEchoSerializer(), 'handler': serverecho.ServerEchoHandler()},
            0x20 : {'name': 'CLIENT_DISCONNECT_WITH_REASON', 'serializer': clientdisconnectwithreason.ClientDisconnectWithReasonSerializer(), 'handler': clientdisconnectwithreason.ClientDisconnectWithReasonHandler()},
            0x21 : {'name': 'CLIENT_CONNECT_READY_TCP', 'serializer': clientconnectreadytcp.ClientConnectReadyTcpSerializer(), 'handler': clientconnectreadytcp.ClientConnectReadyTcpHandler()},
            0x22 : {'name': 'SERVER_CONNECT_REQUIRE', 'serializer': serverconnectrequire.ServerConnectRequireSerializer(), 'handler': serverconnectrequire.ServerConnectRequireHandler()},
            0x23 : {'name': 'CLIENT_CONNECT_READY_REQUIRE', 'serializer': clientconnectreadyrequire.ClientConnectReadyRequireSerializer(), 'handler': clientconnectreadyrequire.ClientConnectReadyRequireHandler()},
            0x24 : {'name': 'CLIENT_HELLO', 'serializer': clienthello.ClientHelloSerializer(), 'handler': clienthello.ClientHelloHandler()},
            0x25 : {'name': 'SERVER_HELLO', 'serializer': serverhello.ServerHelloSerializer(), 'handler': serverhello.ServerHelloHandler()},
            0x26 : {'name': 'SERVER_STARTUP_INFO_NOTIFY', 'serializer': serverstartupinfonotify.ServerStartupInfoNotifySerializer(), 'handler': serverstartupinfonotify.ServerStartupInfoNotifyHandler()},
            0x27 : {'name': 'CLIENT_PEER_QUERY', 'serializer': clientpeerquery.ClientPeerQuerySerializer(), 'handler': clientpeerquery.ClientPeerQueryHandler()},
            0x28 : {'name': 'SERVER_PEER_QUERY_NOTIFY', 'serializer': serverpeerquerynotify.ServerPeerQueryNotifySerializer(), 'handler': serverpeerquerynotify.ServerPeerQueryNotifyHandler()},
            0x29 : {'name': 'CLIENT_PEER_QUERY_LIST', 'serializer': clientpeerquerylist.ClientPeerQueryListSerializer(), 'handler': clientpeerquerylist.ClientPeerQueryListHandler()},
            0x2a : {'name': 'SERVER_PEER_QUERY_LIST_NOTIFY', 'serializer': serverpeerquerylistnotify.ServerPeerQueryListNotifySerializer(), 'handler': serverpeerquerylistnotify.ServerPeerQueryListNotifyHandler()},
            0x2b : {'name': 'CLIENT_WALLCLOCK_QUERY', 'serializer': clientwallclockquery.ClientWallclockQuerySerializer(), 'handler': clientwallclockquery.ClientWallclockQueryHandler()},
            0x2c : {'name': 'SERVER_WALLCLOCK_QUERY_NOTIFY', 'serializer': serverwallclockquerynotify.ServerWallclockQueryNotifySerializer(), 'handler': serverwallclockquerynotify.ServerWallclockQueryNotifyHandler()},
            0x2d : {'name': 'CLIENT_TIMEBASE_QUERY', 'serializer': clienttimebasequery.ClientTimebaseQuerySerializer(), 'handler': clienttimebasequery.ClientTimebaseQueryHandler()},
            0x2e : {'name': 'SERVER_TIMEBASE_QUERY_NOTIFY', 'serializer': servertimebasequerynotify.ServerTimebaseQueryNotifySerializer(), 'handler': servertimebasequerynotify.ServerTimebaseQueryNotifyHandler()},
            0x2f : {'name': 'CLIENT_TOKEN_MESSAGE', 'serializer': clienttokenmessage.ClientTokenMessageSerializer(), 'handler': clienttokenmessage.ClientTokenMessageHandler()},
            0x30 : {'name': 'SERVER_TOKEN_MESSAGE', 'serializer': servertokenmessage.ServerTokenMessageSerializer(), 'handler': servertokenmessage.ServerTokenMessageHandler()},
            0x31 : {'name': 'CLIENT_SYSTEM_MESSAGE', 'serializer': clientsystemmessage.ClientSystemMessageSerializer(), 'handler': clientsystemmessage.ClientSystemMessageHandler()},
            0x32 : {'name': 'CLIENT_APP_BROADCAST_QOS', 'serializer': clientappbroadcastqos.ClientAppBroadcastQosSerializer(), 'handler': clientappbroadcastqos.ClientAppBroadcastQosHandler()},
            0x33 : {'name': 'CLIENT_APP_SINGLE_QOS', 'serializer': clientappsingleqos.ClientAppSingleQosSerializer(), 'handler': clientappsingleqos.ClientAppSingleQosHandler()},
            0x34 : {'name': 'CLIENT_APP_LIST_QOS', 'serializer': clientapplistqos.ClientAppListQosSerializer(), 'handler': clientapplistqos.ClientAppListQosHandler()},
            0x35 : {'name': 'CLIENT_MAX_MSGLEN', 'serializer': clientmaxmsglen.ClientMaxMsglenSerializer(), 'handler': clientmaxmsglen.ClientMaxMsglenHandler()},
            0x36 : {'name': 'SERVER_MAX_MSGLEN', 'serializer': servermaxmsglen.ServerMaxMsglenSerializer(), 'handler': servermaxmsglen.ServerMaxMsglenHandler()}
    }

