sudo apt-get update;
sudo apt-get install zip -y;
sudo apt-get install python3.9 -y;
sudo apt-get install python3.9-venv -y;
screen -XS robo quit;
rm -rf robo;
rm -rf robo_env;
python3.9 -m venv robo_env;
mkdir robo;
unzip robo.zip -d robo/;
rm robo.zip;
cd robo;
rm logs/*;
../robo_env/bin/pip3 install -r requirements.txt;
sed -i 's@.*ip.*@"ip":"0.0.0.0",@g' config.json;
screen -Sdm robo ../robo_env/bin/python3.9 robo.py;
